import type { Recipe } from '@/lib/types';

export const recipes: Recipe[] = [
  {
    id: 'quinoa-salad',
    name: 'Vibrant Quinoa Salad',
    cuisine: 'Mediterranean',
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    ingredients: [
      { item: 'Quinoa', quantity: '1 cup' },
      { item: 'Cucumber', quantity: '1, diced' },
      { item: 'Cherry tomatoes', quantity: '1 cup, halved' },
      { item: 'Red onion', quantity: '1/4, finely chopped' },
      { item: 'Feta cheese', quantity: '1/2 cup, crumbled' },
      { item: 'Lemon juice', quantity: '2 tbsp' },
      { item: 'Olive oil', quantity: '2 tbsp' },
    ],
    instructions: [
      'Cook quinoa according to package directions. Let cool.',
      'In a large bowl, combine cooked quinoa, cucumber, tomatoes, and red onion.',
      'In a small bowl, whisk together lemon juice and olive oil. Pour over salad.',
      'Gently stir in feta cheese. Season with salt and pepper to taste.',
    ],
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    nutrition: { calories: 350, protein: 12, carbs: 40, fat: 18 },
    imageId: 'recipe-1',
  },
  {
    id: 'avocado-toast',
    name: 'Classic Avocado Toast',
    cuisine: 'American',
    dietaryTags: ['Vegetarian'],
    ingredients: [
      { item: 'Sourdough bread', quantity: '2 slices' },
      { item: 'Avocado', quantity: '1, ripe' },
      { item: 'Red pepper flakes', quantity: 'a pinch' },
      { item: 'Salt and pepper', quantity: 'to taste' },
      { item: 'Lemon', quantity: '1 wedge' },
    ],
    instructions: [
      'Toast the bread slices to your desired crispness.',
      'Mash the avocado in a bowl, leaving some chunks for texture.',
      'Squeeze lemon juice into the avocado and mix.',
      'Spread the avocado evenly on the toast.',
      'Sprinkle with red pepper flakes, salt, and pepper.',
    ],
    prepTime: 5,
    cookTime: 5,
    servings: 1,
    nutrition: { calories: 320, protein: 10, carbs: 35, fat: 18 },
    imageId: 'recipe-2',
  },
  {
    id: 'grilled-chicken',
    name: 'Herb Grilled Chicken',
    cuisine: 'American',
    dietaryTags: ['Gluten-Free', 'Keto'],
    ingredients: [
      { item: 'Chicken breast', quantity: '2 boneless, skinless' },
      { item: 'Olive oil', quantity: '1 tbsp' },
      { item: 'Dried rosemary', quantity: '1 tsp' },
      { item: 'Dried thyme', quantity: '1 tsp' },
      { item: 'Garlic powder', quantity: '1/2 tsp' },
    ],
    instructions: [
      'Preheat grill to medium-high heat.',
      'Rub chicken breasts with olive oil and seasonings.',
      'Grill chicken for 6-8 minutes per side, or until cooked through.',
      'Let rest for 5 minutes before slicing.',
    ],
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    nutrition: { calories: 280, protein: 45, carbs: 1, fat: 10 },
    imageId: 'recipe-3',
  },
  {
    id: 'lentil-soup',
    name: 'Hearty Lentil Soup',
    cuisine: 'Mediterranean',
    dietaryTags: ['Vegan', 'Gluten-Free'],
    ingredients: [
      { item: 'Brown lentils', quantity: '1 cup' },
      { item: 'Vegetable broth', quantity: '4 cups' },
      { item: 'Carrot', quantity: '1, chopped' },
      { item: 'Celery', quantity: '1 stalk, chopped' },
      { item: 'Onion', quantity: '1/2, chopped' },
      { item: 'Cumin', quantity: '1 tsp' },
    ],
    instructions: [
      'Sauté onion, carrot, and celery in a large pot until softened.',
      'Add lentils, vegetable broth, and cumin. Bring to a boil.',
      'Reduce heat and simmer for 25-30 minutes, or until lentils are tender.',
      'Season with salt and pepper to taste.',
    ],
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    nutrition: { calories: 250, protein: 15, carbs: 45, fat: 2 },
    imageId: 'recipe-4',
  },
  {
    id: 'berry-smoothie',
    name: 'Morning Berry Smoothie',
    cuisine: 'American',
    dietaryTags: ['Vegan', 'Gluten-Free'],
    ingredients: [
      { item: 'Mixed berries (frozen)', quantity: '1.5 cups' },
      { item: 'Banana', quantity: '1' },
      { item: 'Almond milk', quantity: '1 cup' },
      { item: 'Chia seeds', quantity: '1 tbsp' },
    ],
    instructions: [
      'Combine all ingredients in a blender.',
      'Blend until smooth and creamy.',
      'Pour into a glass and enjoy immediately.',
    ],
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    nutrition: { calories: 300, protein: 5, carbs: 60, fat: 6 },
    imageId: 'recipe-5',
  },
  {
    id: 'spaghetti-aglio-e-olio',
    name: 'Spaghetti Aglio e Olio',
    cuisine: 'Italian',
    dietaryTags: ['Vegetarian'],
    ingredients: [
      { item: 'Spaghetti', quantity: '200g' },
      { item: 'Garlic', quantity: '4 cloves, thinly sliced' },
      { item: 'Olive oil', quantity: '1/4 cup' },
      { item: 'Red pepper flakes', quantity: '1/2 tsp' },
      { item: 'Parsley', quantity: '1/4 cup, chopped' },
    ],
    instructions: [
      'Cook spaghetti according to package directions.',
      'While pasta is cooking, heat olive oil in a pan over medium heat. Add garlic and red pepper flakes.',
      'Cook until garlic is golden, about 2 minutes. Be careful not to burn it.',
      'Drain pasta, reserving 1/2 cup of pasta water.',
      'Add pasta to the pan with the garlic oil. Toss to coat. Add pasta water as needed to create a sauce.',
      'Stir in parsley and serve.',
    ],
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    nutrition: { calories: 450, protein: 10, carbs: 60, fat: 20 },
    imageId: 'recipe-6',
  },
];
