name: Branch Protection for Automated PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main
      - release
      - dev

# Required permissions for Dependabot and other automated PRs
permissions:
  contents: read
  pull-requests: write

jobs:
  validate-automated-prs:
    runs-on: ubuntu-latest
    # Only run for Dependabot and other automated PRs
    if: github.actor == 'dependabot[bot]' || github.actor == 'github-actions[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Allow automated dependency updates
        run: |
          echo "✓ Automated PR from ${{ github.actor }} is allowed"
          echo "Skipping strict branch source validation for automated PRs"

      - name: Validate PR content for security
        run: |
          echo "Validating automated PR content..."
          # Add any specific security checks for automated PRs here
          echo "✓ Basic validation passed for automated PR"