name: Branch Protection

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main
      - release
  push:
    branches:
      - main
      - release

jobs:
  validate-branch-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch source for PR to main
        if: github.base_ref == 'main'
        run: |
          if [ "${{ github.head_ref }}" != "release" ]; then
            echo "ERROR: Only branches from 'release' can be merged into 'main'"
            exit 1
          fi
          echo "✓ PR from 'release' to 'main' is allowed"

      - name: Check branch source for PR to release
        if: github.base_ref == 'release'
        run: |
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "ERROR: Only branches from 'dev' can be merged into 'release'"
            exit 1
          fi
          echo "✓ PR from 'dev' to 'release' is allowed"

      - name: Prevent direct pushes to protected branches
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release')
        run: |
          echo "ERROR: Direct pushes to 'main' and 'release' branches are not allowed."
          echo "All changes must go through pull requests with required checks."
          exit 1
