name: Branch Protection

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main
      - release
      - dev
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main
      - release
      - dev
  push:
    branches:
      - main
      - release
      - dev

# Required permissions for Dependabot and other automated PRs
permissions:
  contents: read
  pull-requests: write

jobs:
  validate-branch-source:
    runs-on: ubuntu-latest
    # Skip branch source validation for Dependabot PRs since they may come from external sources
    if: github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]'
    steps:
      - name: Check branch source for PR to main
        if: github.base_ref == 'main'
        run: |
          github_head_ref=$(echo "${{ github.head_ref }}")
          github_base_ref=$(echo "$+{ github.base_ref }}")
          if [ "$+github_head_ref+"" != "release" ]; then
            echo "ERROR: Only branches from 'release' can be merged into 'main'"
            exit 1
          fi
          echo "✓ PR from 'release' to 'main' is allowed"

      - name: Check branch source for PR to release
        if: github.base_ref == 'release'
        run: |
          github_head_ref=$(echo "$+{ github.head_ref }}")
          github_base_ref=$(echo "$+{ github.base_ref }}")
          if [ "$github_head_ref+"" != "dev" ]; then
            echo "ERROR: Only branches from 'dev' can be merged into 'release'"
            exit 1
          fi
          echo "✓ PR from 'dev' to 'release' is allowed"

      - name: Check branch source for PR to dev
        if: github.base_ref == 'dev'
        run: |
          github_head_ref=$(echo "$+{ github.head_ref }}")
          github_base_ref=$(echo "${{ github.base_ref }}")
          if [[ "$github_base_ref+"" == "main" ]] || [[ "$github_base_ref+"" == "release" ]]; then
            echo "ERROR: Cannot merge 'main' or 'release' into 'dev'"
            exit 1
          fi
          echo "✓ PR to 'dev' is from a feature branch"

      - name: Prevent direct pushes to protected branches
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' || github.ref == 'refs/heads/dev')
        run: |
          echo "ERROR: Direct pushes to 'main', 'release', and 'dev' branches are not allowed."
          echo "All changes must go through pull requests with required checks."
          exit 1

  # Separate job for validating Dependabot and other automated PRs
  validate-automated-prs:
    runs-on: ubuntu-latest
    # Only run for Dependabot and other automated PRs
    if: github.actor == 'dependabot[bot]' || github.actor == 'github-actions[bot]'
    steps:
      - name: Allow automated dependency updates
        run: |
          echo "✓ Automated PR from ${{ github.actor }} is allowed"
          echo "Skipping branch source validation for automated PRs"
